apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: roboshop-microservices
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: mongodb
        path: 1-mongodb
<<<<<<< HEAD
        wave: "1"
      - name: redis
        path: 2-redis
        wave: "1"
      - name: mysql
        path: 3-mysql
        wave: "1"
      - name: rabbitmq
        path: 4-rabbitmq
        wave: "1"
      - name: catalogue
        path: 5-catalogue
        wave: "2"
      - name: user
        path: 6-user
        wave: "2"
      - name: cart
        path: 7-cart
        wave: "3"
      - name: shipping
        path: 8-shipping
        wave: "2"
      - name: payment
        path: 9-payment
        wave: "2"
      - name: frontend
        path: 10-frontend
        wave: "4"
=======
      - name: redis
        path: 2-redis
      - name: mysql
        path: 3-mysql
      - name: rabbitmq
        path: 4-rabbitmq
      - name: catalogue
        path: 5-catalogue
      - name: user
        path: 6-user
      - name: cart
        path: 7-cart
      - name: shipping
        path: 8-shipping
      - name: payment
        path: 9-payment
      - name: frontend
        path: 10-frontend
>>>>>>> 2541327d7200702d3667d226bdfd726ebc5d962e
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sivaram-ops/cd-roboshop.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
