# statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Chart.Name }}-statefulset"
  labels:
    app: "{{ .Chart.Name }}-statefulset"
spec:
  serviceName: {{ .Values.service.name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        {{- toYaml .Values.containerPorts | nindent 8 }}
        env:
        {{- toYaml .Values.env | nindent 8}}
        volumeMounts:
        - name: {{ .Values.storage.name }}
          mountPath: {{ .Values.storage.mountPath }}
      # volumes:
      #   - name: rabbitmq-volume
      #     persistentVolumeClaim:
      #       claimName: rabbitmq-pvc-0
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.storage.name }}
    spec:
      storageClassName: {{ .Values.storage.className }}
      accessModes: [ {{ .Values.storage.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}
---