# Persistent volume.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-mongodb-pv"
  labels:
    app: roboshop
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.hostPath }}
  persistentVolumeReclaimPolicy: Retain
---